[package]
name = "httpforge"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.25"
anyhow = "1.0.95"
env_logger = "0.11.6"
